name:                c-is-for-coding
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- process >= 1.6 && < 1.7
- gloss >= 1.13
- directory >= 1.3
when:
- condition: os(linux)
  dependencies:
    - unix >= 2.5
- condition: os(darwin)
  dependencies:
    - unix >= 2.5

library:
  source-dirs: src

executables:
  c-is-for-coding-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-is-for-coding

tests:
  c-is-for-coding-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-is-for-coding
    - tasty
    - tasty-hunit
