name:                fast-func-utils
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- unordered-containers == 0.2.*
- split == 0.2.*

library:
  source-dirs: src

executables:
  fast-func-utils-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fast-func-utils

tests:
  fast-func-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fast-func-utils
    - tasty
    - tasty-hunit
