name:                fast-func-gui
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- aeson == 2.0.*
- gi-gtk == 3.0.*
- Cabal == 3.*
- haskell-gi-base == 0.25.0
- req == 3.9.*
- text == 1.2.*
# when:
# - condition: os(linux)
#   dependencies:
#     - unix >= 2.5
# - condition: os(darwin)
#   dependencies:
#     - unix >= 2.5

library:
  source-dirs: src

executables:
  fast-func-gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fast-func-gui

tests:
  fast-func-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fast-func-gui
    - tasty
    - tasty-hunit
