[package]
name = "utils-rs"
version = "0.1.0"
authors = ["Philippe Solodov <solop1906@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
swipl = "0.3.11"